# Fly.io configuration for RizzGPT Clone Backend
app = "rizzgpt-clone-backend"
primary_region = "iad"  # Washington D.C. for low latency to US users

[build]
  dockerfile = "Dockerfile"
  ignorefile = ".dockerignore"

[env]
  ENVIRONMENT = "production"
  HOST = "0.0.0.0"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[[vm.http_service.concurrency]]
  type = "connections"
  hard_limit = 100
  soft_limit = 80

[deploy]
  release_command = "echo 'Deployment starting...'"
  strategy = "rolling"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "30s"
    restart_limit = 0
    timeout = "5s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "10s"
    method = "GET"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "5s"
    tls_skip_verify = false

    [services.http_checks.headers]
      User-Agent = "fly-health-check"